[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  functionsPort = 9999
  framework = "#custom"
  autoLaunch = true

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Set environment variables for the build
[build.environment]
  VITE_BACKEND_URL = "/.netlify/functions"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 