<template>
    <div class="container py-4">
        <h1 class="mb-4 fw-bold">Terms of Service</h1>
        <p class="text-muted mb-4">Last updated: July 17, 2025</p>

        <h2 class="mb-4 fw-bold">Terms of Service for Somni Personality Analyzer</h2>

        <p>Welcome to Somni Personality Analyzer! These Terms of Service ("Terms") govern your access to and use of our
            mobile application and any related services (collectively, the "Service") operated by us (the "Developer,"
            "we," or "us"). By downloading, installing, or using the Service, you agree to be bound by these Terms. If
            you do not agree, please do not use the Service.</p>

        <h3>1. Eligibility</h3>
        <p>You must be at least 13 years old (or the minimum age of digital consent in your jurisdiction) to use the
            Service. By using it, you represent and warrant that you meet this age requirement.</p>

        <h3>2. Account Registration & Google SSO</h3>
        <h4>Registration:</h4>
        <p>You may register using Google Single Sign-On (SSO). By doing so, you authorize us to collect and store the
            profile information that Google provides (name, email, profile picture).</p>

        <h4>Account Security:</h4>
        <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities
            under your account. Notify us immediately of any unauthorized use.</p>

        <h3>3. Service Tiers & Subscription</h3>
        <h4>Free Tier:</h4>
        <p>Access to basic personality questions and standard AI-generated insights.</p>

        <h4>Premium Tier:</h4>
        <p>Unlock advanced insights and features by subscribing.</p>

        <h4>Payment Processing:</h4>
        <p>All payments are handled through Stripe. We only receive payment tokens and subscription status; we never see
            or store your full payment card data.</p>

        <h4>Billing & Refunds:</h4>
        <p>Subscription fees are charged in advance on a recurring basis (monthly or annual, as selected). All fees are
            non-refundable except as required by law.</p>

        <h3>4. User Content & AI Processing</h3>
        <h4>Personality Responses:</h4>
        <p>You answer non-identifying, multiple-choice personality questions (e.g., "rarely," "sometimes," "often").</p>

        <h4>Data Usage:</h4>
        <p>Your responses (without your name or email) are transmitted to OpenAI's API for analysis. By using the
            Service, you grant us permission to do so.</p>

        <h4>Content Ownership:</h4>
        <p>You retain ownership of any input you provide. We retain ownership of all AI-generated outputs and
            improvements to the Service.</p>

        <h3>5. Intellectual Property</h3>
        <p>All software, design, graphics, text, and other materials in the Service are owned by us or our licensors and
            are protected by copyright, trademark, and other laws. You may not reproduce, distribute, modify, or create
            derivative works without our express written permission.</p>

        <h3>6. Prohibited Conduct</h3>
        <p>You agree not to:</p>
        <ul>
            <li>Reverse-engineer, decompile, or otherwise attempt to extract the source code of the Service.</li>
            <li>Circumvent or interfere with any security or authentication mechanism.</li>
            <li>Use the Service for any unlawful purpose or in violation of applicable laws.</li>
            <li>Share your account or grant access to unauthorized users.</li>
        </ul>

        <h3>7. Disclaimers & Warranties</h3>
        <h4>"As Is":</h4>
        <p>The Service is provided "as is" and "as available," without warranties of any kind.</p>

        <h4>No Guarantee:</h4>
        <p>We do not guarantee that the Service will be error-free, uninterrupted, or secure.</p>

        <h4>AI Insights:</h4>
        <p>The personality insights generated by AI are for entertainment and informational purposes only and should not
            be construed as professional advice.</p>

        <h3>8. Limitation of Liability</h3>
        <p>To the fullest extent permitted by law, in no event shall we be liable for any indirect, incidental, special,
            consequential, or punitive damages arising out of your use of, or inability to use, the Service—even if we
            have been advised of the possibility of such damages.</p>

        <h3>9. Indemnification</h3>
        <p>You agree to indemnify and hold us harmless from any claims, losses, liabilities, damages, costs, or expenses
            (including reasonable attorneys' fees) arising out of or related to:</p>
        <ul>
            <li>Your breach of these Terms.</li>
            <li>Your use of the Service.</li>
            <li>Your violation of any applicable law or the rights of any third party.</li>
        </ul>

        <h3>10. Termination</h3>
        <p>We may suspend or terminate your access to the Service at any time, with or without cause or notice. Upon
            termination, all licenses and rights granted to you under these Terms will immediately cease.</p>

        <h3>11. Changes to the Terms</h3>
        <p>We reserve the right to modify these Terms at any time. We will post the revised Terms here with an updated
            "Last updated" date. Your continued use of the Service after changes are posted constitutes your acceptance
            of the new Terms.</p>

        <h3>12. Governing Law & Dispute Resolution</h3>
        <p>These Terms are governed by the laws of the United States, without regard to its conflict-of-law principles.
            Any dispute arising out of or relating to these Terms shall be subject to the exclusive jurisdiction of the
            courts located in the United States.</p>

        <h3>13. Contact Information</h3>
        <p>If you have any questions about these Terms, please contact us at:</p>
        <p>Email: <a href="mailto:rvniemela@hotmail.com">rvniemela@hotmail.com</a></p>
    </div>
</template>

<script setup lang="ts">
</script>

<style scoped>
.container {
    max-width: 1200px;
}

h1 {
    color: var(--text-primary);
}

.card {
    border: none;
    box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075);
}

ul {
    padding-left: 1.5rem;
}

li {
    margin-bottom: 0.5rem;
}

h3 {
    color: var(--text-primary);
    margin-top: 2rem;
    margin-bottom: 1rem;
}

h4 {
    margin-top: 1rem;
    margin-bottom: 0.5rem;
}

p {
    margin-bottom: 1rem;
}
</style>